export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    SET_FRONTPAGE_DATA:'SET_FRONTPAGE_DATA',
    SET_SHOPS_DATA:'SET_SHOPS_DATA'
  };